server:
  port: 0
  index: 1       # 集群下的服务器索引、用来唯一化instance-id以及避免重复执行工作
  tomcat: 
    max-threads: 10

mybatis: 
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.ex.model.entity.*
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      
spring:
   main:
      allow-bean-definition-overriding: true
   application:
      name: eotc-mgs
   messages:
    basename: templete
    encoding: UTF-8
    cache-duration: 3600
   jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
   datasource:
    url: jdbc:mysql:///mgs?useAffectedRows=true&useUnicode=yes&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&amp
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver     
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 4
      minimum-idle: 1
      idle-timeout: 180000
      connection-timeout: 5000 
   redis: 
     database: 0  
     host:
     port: 6379  
     jedis: 
      pool: 
       max-active: 200 
       max-wait: -1 
       max-idle: 10 
       min-idle: 1  
     timeout: 1000
     password:


#消息配置
app:
  message:
    #美联
    ml:
      domain:
      smsApiUser:
      smsApiKey:
      smsApiPassword:
      smsApiUrl: http://hk.5c.com.cn/api/send/index.php
    #赛邮
    sy:
      smsSyAppId:
      smsSySignature:
      smsSyApiUrl: https://api.mysubmail.com/message/send
    email:
      emailFrom:
      emailNickName:
      emailUserName:
      emailPassword:
      emailProtocol:
      emailHost:
      emailPort:
      emailSslEnable: false
    maxFailResendTime: 3
    channel: 1
    times: 20
#日志信息
logging: 
  config: classpath:logback-spring.xml
  path: /tmp/logs/mgs
